from __future__ import annotations

from copy import deepcopy
from typing import Any


PERSONAS: dict[str, dict[str, Any]] = {
    "customer_success": {
        "id": "customer_success",
        "label": "Customer Success Manager",
        "domain": "B2B SaaS Customer Success",
        "entity_label": "Customer",
        "decision_type": "Renewal Risk",
        "required_fields": ["health_score", "renewal_date", "contract_value", "segment"],
        "kpis": [
            {"label": "Health Score", "key": "health_score", "suffix": "%"},
            {"label": "Contract Value", "key": "contract_value", "prefix": "$"},
            {"label": "Renewal Date", "key": "renewal_date"},
            {"label": "Usage Trend", "key": "usage_trend"},
        ],
        "decision_matrix_columns": ["Action", "Success", "Revenue Impact", "Risk", "Owner", "Evidence"],
        "business_labels": {
            "success_metric": "Renewal success",
            "risk_metric": "Churn risk",
            "impact_metric": "Revenue impact",
        },
        "risk_thresholds": [
            {"metric": "health_score", "operator": "lt", "value": 60, "label": "Low customer health", "severity": "High", "weight": 18},
        ],
        "actions": [
            {
                "action": "Schedule executive value workshop",
                "owner": "Customer Success Manager + Account Executive",
                "impact": "High retention, low margin loss",
                "risk_level": "Low",
                "base_success": 66,
                "max_success": 92,
                "decision_drivers": ["Value Realization", "Executive Alignment", "Pricing Concern", "Competitor Evaluation", "Renewal Risk"],
                "avoid_when": ["Confirmed Budget Freeze"],
                "evidence": ["Pricing policy prefers value alignment before discounts.", "Renewal playbook recommends executive alignment for strategic renewals."],
                "reasoning": "Addresses renewal risk by proving business value before changing commercial terms.",
            },
            {
                "action": "Launch technical success recovery plan",
                "owner": "Solutions Engineer + Support Lead",
                "impact": "Medium retention, operational cost",
                "risk_level": "Medium",
                "base_success": 58,
                "max_success": 86,
                "decision_drivers": ["Support Risk", "Technical Blocker", "Adoption Risk", "Implementation Concern"],
                "avoid_when": ["Pure Commercial Objection"],
                "evidence": ["Support escalation guidelines require a named owner and customer-visible recovery plan."],
                "reasoning": "Best when technical blockers or service issues are the main renewal barrier.",
            },
            {
                "action": "Offer targeted renewal discount",
                "owner": "Account Executive + Finance Approval",
                "impact": "Medium retention, direct margin loss",
                "risk_level": "Medium",
                "base_success": 52,
                "max_success": 82,
                "decision_drivers": ["Confirmed Budget Constraint", "Procurement Blocker", "Commercial Approval"],
                "avoid_when": ["Unproven Value", "Support Risk"],
                "evidence": ["Discount policy requires approval and should follow value alignment."],
                "reasoning": "Useful only when budget is the real blocker and value has already been confirmed.",
            },
        ],
        "knowledge_docs": [
            {
                "id": "cs-renewal-playbook",
                "title": "Enterprise Renewal Risk Playbook",
                "source_type": "playbook",
                "tags": ["customer_success", "renewal", "churn", "executive alignment", "value realization"],
                "content": "When an enterprise customer raises renewal concerns, the team should identify value gaps, involve executive sponsors, review adoption, and create a mutual success plan before commercial concessions.",
            },
            {
                "id": "cs-pricing-policy",
                "title": "Strategic Account Pricing Policy",
                "source_type": "policy",
                "tags": ["customer_success", "pricing", "discount", "commercial approval"],
                "content": "Strategic renewal discounts require approval and should be used after value alignment, churn risk review, and commercial impact analysis.",
            },
            {
                "id": "cs-support-escalation",
                "title": "Support Escalation Guidelines",
                "source_type": "guideline",
                "tags": ["customer_success", "support", "technical blocker", "escalation"],
                "content": "When unresolved technical or support issues affect renewal confidence, create a customer-visible recovery plan with owner, deadline, and checkpoint.",
            },
        ],
        "memory_cases": [
            {
                "id": "cs-spotify-workshop-renewed",
                "customer_name": "Spotify",
                "industry": "Media",
                "segment": "Enterprise",
                "problem": "Renewal risk with pricing concern and competitor evaluation",
                "recommendation": "Executive value workshop",
                "outcome": "Renewed",
                "confidence": 92,
                "tags": ["customer_success", "renewal risk", "value realization", "executive alignment"],
                "summary": "Executive value workshop connected platform usage to business impact and the customer renewed without an immediate discount.",
            },
            {
                "id": "cs-acme-support-churned",
                "customer_name": "Acme Logistics",
                "industry": "Logistics",
                "segment": "Enterprise",
                "problem": "Renewal risk with unresolved support issues",
                "recommendation": "Standard account follow-up",
                "outcome": "Churned",
                "confidence": 63,
                "tags": ["customer_success", "support risk", "churn"],
                "summary": "The team did not create a visible technical recovery plan and the customer churned.",
            },
        ],
    },
    "sales": {
        "id": "sales",
        "label": "Sales Manager",
        "domain": "Enterprise Sales",
        "entity_label": "Account",
        "decision_type": "Stalled Deal",
        "required_fields": ["deal_value", "stage", "days_stalled", "competitor"],
        "kpis": [
            {"label": "Deal Value", "key": "deal_value", "prefix": "$"},
            {"label": "Stage", "key": "stage"},
            {"label": "Days Stalled", "key": "days_stalled"},
            {"label": "Competitor", "key": "competitor"},
        ],
        "decision_matrix_columns": ["Action", "Win Probability", "Deal Impact", "Risk", "Owner", "Evidence"],
        "business_labels": {
            "success_metric": "Win probability",
            "risk_metric": "Deal risk",
            "impact_metric": "Pipeline impact",
        },
        "risk_thresholds": [
            {"metric": "days_stalled", "operator": "gt", "value": 14, "label": "Deal stalled beyond threshold", "severity": "High", "weight": 18},
        ],
        "actions": [
            {
                "action": "Schedule security-led technical validation workshop",
                "owner": "Sales Manager + Solutions Engineer",
                "impact": "High win probability improvement",
                "risk_level": "Low",
                "base_success": 64,
                "max_success": 90,
                "decision_drivers": ["Security Concern", "Compliance Concern", "Technical Validation", "Trust Gap"],
                "avoid_when": ["Pure Pricing Objection"],
                "evidence": ["Security validation process recommends technical workshop for compliance blockers."],
                "reasoning": "Resolves trust and technical blockers before commercial negotiation.",
            },
            {
                "action": "Escalate executive sponsor alignment",
                "owner": "VP Sales + Account Executive",
                "impact": "High influence, medium relationship risk",
                "risk_level": "Medium",
                "base_success": 56,
                "max_success": 82,
                "decision_drivers": ["Decision Maker Gap", "Executive Alignment", "Authority Risk", "Strategic Deal"],
                "avoid_when": ["Low Deal Value"],
                "evidence": ["Enterprise sales playbook recommends executive mapping for strategic stalled deals."],
                "reasoning": "Useful when authority or executive sponsorship is blocking deal progress.",
            },
            {
                "action": "Offer limited pricing incentive",
                "owner": "Account Executive + Finance Approval",
                "impact": "Medium win improvement, margin loss",
                "risk_level": "High",
                "base_success": 48,
                "max_success": 78,
                "decision_drivers": ["Budget Constraint", "Procurement Blocker", "Commercial Negotiation"],
                "avoid_when": ["Security Concern", "Trust Gap"],
                "evidence": ["Discount policy warns against early discounting before trust and value are confirmed."],
                "reasoning": "Useful only when budget is the primary blocker.",
            },
        ],
        "knowledge_docs": [
            {
                "id": "sales-enterprise-playbook",
                "title": "Enterprise Sales Playbook",
                "source_type": "playbook",
                "tags": ["sales", "stalled deal", "executive alignment", "decision maker"],
                "content": "For stalled enterprise deals, diagnose the real blocker, map decision makers, involve technical experts for product risk, and avoid discounting until value and trust are confirmed.",
            },
            {
                "id": "sales-security-validation",
                "title": "Security Validation Process",
                "source_type": "process",
                "tags": ["sales", "security concern", "compliance concern", "technical validation"],
                "content": "Security and compliance objections require structured validation with solutions engineering, security leads, and the account executive.",
            },
        ],
        "memory_cases": [
            {
                "id": "sales-atlas-security-closed",
                "customer_name": "Atlas Bank",
                "industry": "Financial Services",
                "segment": "Enterprise",
                "problem": "Deal stalled due to security and compliance concerns",
                "recommendation": "Security-led technical validation workshop",
                "outcome": "Moved to procurement",
                "confidence": 89,
                "tags": ["sales", "security concern", "technical validation", "procurement"],
                "summary": "Security workshop resolved buyer concerns and moved the account into procurement.",
            },
            {
                "id": "sales-northstar-discount-lost",
                "customer_name": "Northstar Retail",
                "industry": "Retail",
                "segment": "Enterprise",
                "problem": "Deal stalled with unresolved trust concerns",
                "recommendation": "Early pricing discount",
                "outcome": "Lost",
                "confidence": 61,
                "tags": ["sales", "discount", "trust gap", "lost"],
                "summary": "The team discounted before resolving trust concerns and lost to a competitor.",
            },
        ],
    },
    "healthcare": {
        "id": "healthcare",
        "label": "Healthcare Administrator",
        "domain": "Hospital Operations",
        "entity_label": "Unit",
        "decision_type": "Capacity Risk",
        "required_fields": ["occupancy_rate", "available_beds", "discharge_queue", "staffing_gap"],
        "kpis": [
            {"label": "Occupancy", "key": "occupancy_rate", "suffix": "%"},
            {"label": "Available Beds", "key": "available_beds"},
            {"label": "Discharge Queue", "key": "discharge_queue"},
            {"label": "Staffing Gap", "key": "staffing_gap"},
        ],
        "decision_matrix_columns": ["Action", "Capacity Impact", "Patient Flow Risk", "Cost", "Owner", "Evidence"],
        "business_labels": {
            "success_metric": "Capacity improvement",
            "risk_metric": "Patient flow risk",
            "impact_metric": "Operational impact",
        },
        "risk_thresholds": [
            {"metric": "occupancy_rate", "operator": "gt", "value": 85, "label": "High occupancy", "severity": "High", "weight": 20},
            {"metric": "staffing_gap", "operator": "gt", "value": 0, "label": "Staffing gap", "severity": "Medium", "weight": 12},
        ],
        "actions": [
            {
                "action": "Activate discharge coordination huddle",
                "owner": "Hospital Operations Lead + Charge Nurse",
                "impact": "High capacity improvement, low cost",
                "risk_level": "Low",
                "base_success": 64,
                "max_success": 88,
                "decision_drivers": ["High Occupancy", "Discharge Delay", "Patient Flow Bottleneck", "Transport Blocker", "Documentation Blocker"],
                "avoid_when": ["Clinical Instability"],
                "evidence": ["Discharge coordination SOP recommends huddles when capacity risk is high."],
                "reasoning": "Coordinates operational blockers without making clinical decisions.",
            },
            {
                "action": "Transfer stable patients to step-down unit",
                "owner": "Clinical Operations + Unit Manager",
                "impact": "Medium capacity improvement",
                "risk_level": "Medium",
                "base_success": 52,
                "max_success": 80,
                "decision_drivers": ["Bed Shortage", "Step-down Eligible", "Patient Flow Bottleneck"],
                "avoid_when": ["Clinical Instability", "No Step-down Capacity"],
                "evidence": ["Patient flow playbook supports step-down transfer when patients meet criteria."],
                "reasoning": "Improves capacity when appropriate operational criteria are met.",
            },
            {
                "action": "Delay elective admissions",
                "owner": "Hospital Administrator",
                "impact": "High capacity impact, high business impact",
                "risk_level": "High",
                "base_success": 42,
                "max_success": 74,
                "decision_drivers": ["Critical Capacity Risk", "Emergency Pressure"],
                "avoid_when": ["Moderate Capacity Risk"],
                "evidence": ["Capacity policy treats elective delay as a last-resort action."],
                "reasoning": "Last-resort action when capacity risk becomes critical.",
            },
        ],
        "knowledge_docs": [
            {
                "id": "health-bed-capacity",
                "title": "Bed Capacity Management Policy",
                "source_type": "policy",
                "tags": ["healthcare", "high occupancy", "bed shortage", "capacity risk"],
                "content": "When occupancy exceeds threshold, operations should trigger capacity review, discharge coordination, and escalation before delaying elective admissions.",
            },
            {
                "id": "health-discharge-sop",
                "title": "Discharge Coordination SOP",
                "source_type": "sop",
                "tags": ["healthcare", "discharge delay", "patient flow bottleneck", "transport blocker"],
                "content": "Discharge huddles should prioritize transport-ready patients, pharmacy blockers, documentation gaps, and family pickup coordination.",
            },
        ],
        "memory_cases": [
            {
                "id": "health-surgical-huddle-improved",
                "customer_name": "Surgical Ward A",
                "industry": "Healthcare",
                "segment": "Hospital Operations",
                "problem": "High occupancy with delayed discharges",
                "recommendation": "Discharge coordination huddle",
                "outcome": "Improved capacity",
                "confidence": 87,
                "tags": ["healthcare", "high occupancy", "discharge delay", "improved capacity"],
                "summary": "Morning discharge huddle removed transport and documentation blockers, freeing beds same day.",
            },
        ],
    },
    "hr": {
        "id": "hr",
        "label": "HR Manager",
        "domain": "People Operations",
        "entity_label": "Employee",
        "decision_type": "Retention Risk",
        "required_fields": ["engagement_score", "workload_level", "tenure_months", "manager_checkins"],
        "kpis": [
            {"label": "Engagement", "key": "engagement_score", "suffix": "%"},
            {"label": "Workload", "key": "workload_level"},
            {"label": "Tenure", "key": "tenure_months", "suffix": " mo"},
            {"label": "Check-ins", "key": "manager_checkins"},
        ],
        "decision_matrix_columns": ["Action", "Retention Impact", "Cost", "Risk", "Owner", "Evidence"],
        "business_labels": {
            "success_metric": "Retention impact",
            "risk_metric": "Attrition risk",
            "impact_metric": "People impact",
        },
        "risk_thresholds": [
            {"metric": "engagement_score", "operator": "lt", "value": 60, "label": "Low engagement", "severity": "High", "weight": 18},
        ],
        "actions": [
            {
                "action": "Create structured retention plan",
                "owner": "HR Manager + Direct Manager",
                "impact": "High retention impact, low cost",
                "risk_level": "Low",
                "base_success": 62,
                "max_success": 88,
                "decision_drivers": ["High Workload", "Career Stagnation", "Growth Concern", "Manager Support Gap", "Recognition Concern", "Attrition Risk"],
                "avoid_when": ["Compensation Only"],
                "evidence": ["Retention playbook recommends early manager intervention for workload and growth concerns."],
                "reasoning": "Addresses workload, growth path, recognition, and manager support before disengagement increases.",
            },
            {
                "action": "Assign mentor and internal mobility path",
                "owner": "HR Manager + Functional Leader",
                "impact": "Medium retention impact",
                "risk_level": "Medium",
                "base_success": 52,
                "max_success": 78,
                "decision_drivers": ["Career Stagnation", "Growth Concern", "Learning Need", "Internal Mobility"],
                "avoid_when": ["Severe Burnout"],
                "evidence": ["Internal mobility guidelines support mentor assignment for growth-risk employees."],
                "reasoning": "Useful when the main concern is growth, learning, or career path.",
            },
            {
                "action": "Open compensation review",
                "owner": "HR Business Partner + Compensation Team",
                "impact": "Medium retention impact, high cost",
                "risk_level": "Medium",
                "base_success": 48,
                "max_success": 80,
                "decision_drivers": ["Compensation Concern", "External Offer", "Market Pay Gap"],
                "avoid_when": ["Workload Risk", "Manager Support Gap"],
                "evidence": ["Compensation policy recommends confirming root cause before adjustment."],
                "reasoning": "Useful when compensation is the primary reason for attrition risk.",
            },
        ],
        "knowledge_docs": [
            {
                "id": "hr-retention-playbook",
                "title": "Employee Retention Playbook",
                "source_type": "playbook",
                "tags": ["hr", "retention risk", "high workload", "growth concern", "manager support"],
                "content": "Early retention action should diagnose workload, manager support, growth path, recognition, and compensation concerns before attrition risk becomes urgent.",
            },
            {
                "id": "hr-workload-policy",
                "title": "Workload Risk Policy",
                "source_type": "policy",
                "tags": ["hr", "workload risk", "burnout", "manager support"],
                "content": "High workload signals require manager check-in, priority reset, and follow-up within two weeks.",
            },
            {
                "id": "hr-mobility-guide",
                "title": "Internal Mobility Guidelines",
                "source_type": "guideline",
                "tags": ["hr", "career stagnation", "growth concern", "internal mobility"],
                "content": "Employees with growth concerns should receive transparent career-path discussion, mentorship, and internal opportunity review.",
            },
        ],
        "memory_cases": [
            {
                "id": "hr-engineer-retention-stayed",
                "customer_name": "Senior Engineer",
                "industry": "Technology",
                "segment": "People Operations",
                "problem": "Retention risk from high workload and growth concerns",
                "recommendation": "Structured retention plan",
                "outcome": "Stayed",
                "confidence": 84,
                "tags": ["hr", "retention risk", "high workload", "growth concern", "stayed"],
                "summary": "Manager reset workload, created growth plan, and employee stayed.",
            },
            {
                "id": "hr-wait-attrition",
                "customer_name": "Product Designer",
                "industry": "Technology",
                "segment": "People Operations",
                "problem": "Low engagement and no timely manager action",
                "recommendation": "Wait until next review cycle",
                "outcome": "Resigned",
                "confidence": 52,
                "tags": ["hr", "attrition risk", "low engagement", "resigned"],
                "summary": "Delayed intervention led to resignation before quarterly review.",
            },
        ],
    },
    "operations": {
        "id": "operations",
        "label": "Operations Manager",
        "domain": "Supply Chain Operations",
        "entity_label": "Supplier",
        "decision_type": "Delivery Risk",
        "required_fields": ["inventory_buffer", "supplier_score", "delay_days", "sla_deadline"],
        "kpis": [
            {"label": "Inventory Buffer", "key": "inventory_buffer"},
            {"label": "Supplier Score", "key": "supplier_score", "suffix": "%"},
            {"label": "Delay Days", "key": "delay_days"},
            {"label": "SLA Deadline", "key": "sla_deadline"},
        ],
        "decision_matrix_columns": ["Action", "Delivery Success", "Cost", "SLA Risk", "Owner", "Evidence"],
        "business_labels": {
            "success_metric": "Delivery success",
            "risk_metric": "SLA risk",
            "impact_metric": "Operational impact",
        },
        "risk_thresholds": [
            {"metric": "supplier_score", "operator": "lt", "value": 70, "label": "Low supplier reliability", "severity": "High", "weight": 18},
            {"metric": "delay_days", "operator": "gt", "value": 2, "label": "Material delivery delay", "severity": "High", "weight": 20},
        ],
        "actions": [
            {
                "action": "Split fulfillment with alternate supplier and expedited shipment",
                "owner": "Operations Manager + Procurement Lead",
                "impact": "High delivery protection, medium cost",
                "risk_level": "Low",
                "base_success": 64,
                "max_success": 90,
                "decision_drivers": ["Supplier Delay", "Low Inventory Buffer", "SLA Exposure", "Customer Impact", "Repeat Supplier Risk"],
                "avoid_when": ["No Alternate Supplier"],
                "evidence": ["Supplier escalation SOP recommends alternate fulfillment when repeat delay threatens SLA."],
                "reasoning": "Protects the SLA while reducing dependence on the delayed supplier.",
            },
            {
                "action": "Use emergency inventory reserve",
                "owner": "Warehouse Lead + Operations Manager",
                "impact": "Medium delivery protection, high buffer cost",
                "risk_level": "Medium",
                "base_success": 54,
                "max_success": 82,
                "decision_drivers": ["Low Inventory Buffer", "Customer Impact", "SLA Exposure"],
                "avoid_when": ["Future Stockout Risk"],
                "evidence": ["Inventory buffer policy allows emergency reserve only for high-priority accounts."],
                "reasoning": "Can protect delivery but may create downstream stockout risk.",
            },
            {
                "action": "Wait for original supplier update",
                "owner": "Supplier Manager",
                "impact": "Low cost, high SLA risk",
                "risk_level": "High",
                "base_success": 36,
                "max_success": 68,
                "decision_drivers": ["Low Urgency", "Reliable Supplier", "No SLA Exposure"],
                "avoid_when": ["Supplier Delay", "SLA Exposure", "Customer Impact"],
                "evidence": ["SLA risk playbook warns against waiting when delay history repeats."],
                "reasoning": "Low-cost option but risky under customer-impacting delivery pressure.",
            },
        ],
        "knowledge_docs": [
            {
                "id": "ops-supplier-escalation",
                "title": "Supplier Escalation SOP",
                "source_type": "sop",
                "tags": ["operations", "supplier delay", "alternate supplier", "sla exposure"],
                "content": "If supplier delay threatens high-priority delivery or SLA, evaluate alternate suppliers, expedited shipment, and customer communication within 24 hours.",
            },
            {
                "id": "ops-inventory-buffer",
                "title": "Inventory Buffer Policy",
                "source_type": "policy",
                "tags": ["operations", "low inventory buffer", "stockout risk"],
                "content": "Emergency inventory can be used only when customer impact or SLA penalty outweighs future stockout risk.",
            },
        ],
        "memory_cases": [
            {
                "id": "ops-alternate-supplier-protected",
                "customer_name": "Tier-1 Supplier Delay",
                "industry": "Manufacturing",
                "segment": "Supply Chain",
                "problem": "Supplier delay threatened high-priority customer SLA",
                "recommendation": "Alternate supplier and expedited shipment",
                "outcome": "SLA protected",
                "confidence": 88,
                "tags": ["operations", "supplier delay", "sla exposure", "alternate supplier"],
                "summary": "Alternate supplier split and expedited shipment protected the delivery SLA.",
            },
        ],
    },
}


def get_persona(persona_id: str | None) -> dict[str, Any]:
    if persona_id and persona_id in PERSONAS:
        return PERSONAS[persona_id]
    return PERSONAS["customer_success"]


def all_knowledge_docs() -> list[dict[str, Any]]:
    docs: list[dict[str, Any]] = []
    for persona in PERSONAS.values():
        for doc in persona["knowledge_docs"]:
            item = deepcopy(doc)
            item["domain"] = persona["domain"]
            item["tags"] = list(dict.fromkeys([persona["id"], persona["label"], persona["domain"], *item["tags"]]))
            docs.append(item)
    return docs


def all_memory_cases() -> list[dict[str, Any]]:
    cases: list[dict[str, Any]] = []
    for persona in PERSONAS.values():
        for case in persona["memory_cases"]:
            item = deepcopy(case)
            item["tags"] = list(dict.fromkeys([persona["id"], persona["label"], persona["domain"], *item["tags"]]))
            cases.append(item)
    return cases

